//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnector
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayLaterEntities : DbContext
    {
        public PayLaterEntities()
            : base("name=PayLaterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PYL_T_PNR_FARE> PYL_T_PNR_FARE { get; set; }
        public virtual DbSet<PYL_T_TICKET> PYL_T_TICKET { get; set; }
        public virtual DbSet<PYL_T_PAYMENT> PYL_T_PAYMENT { get; set; }
        public virtual DbSet<PYL_M_RECONCILIATION_PAYMENT> PYL_M_RECONCILIATION_PAYMENT { get; set; }
        public virtual DbSet<PYL_T_RECONCILIATION_PAYMENT_DETAIL> PYL_T_RECONCILIATION_PAYMENT_DETAIL { get; set; }
        public virtual DbSet<PYL_M_UTC_TIME> PYL_M_UTC_TIME { get; set; }
        public virtual DbSet<PYL_T_BANK_OFFICEID> PYL_T_BANK_OFFICEID { get; set; }
    }
}
