//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYL_T_RECONCILIATION_PAYMENT_DETAIL
    {
        public int ReconciliationPaymentId { get; set; }
        public string BranchCode { get; set; }
        public string BankRef { get; set; }
        public int PaymentId { get; set; }
        public string Pnr { get; set; }
        public string Currency { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int ResponseCode { get; set; }
        public string CustomerName { get; set; }
        public string IdNumber { get; set; }
    }
}
