//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYL_T_PAYMENT
    {
        public int PaymentId { get; set; }
        public string Pnr { get; set; }
        public decimal TotalAmountOriginal { get; set; }
        public string CurrencyOriginal { get; set; }
        public Nullable<decimal> TotalAmountDestination { get; set; }
        public string CurrencyDestination { get; set; }
        public string BankRef { get; set; }
        public string BankCode { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public int ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
    }
}
