//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYL_T_TICKET
    {
        public int PaymentId { get; set; }
        public string TicketNo { get; set; }
        public string PassengerType { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
        public string Currency { get; set; }
    }
}
