//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYL_T_BANK_OFFICEID
    {
        public string BankCode { get; set; }
        public string OfficeId { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> ItineraryInfoShown { get; set; }
    }
}
