//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayLater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_REQUESTS
    {
        public int Id { get; set; }
        public string Requester { get; set; }
        public string RequesterInfo { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
